# Generated by Django 2.2.7 on 2019-11-14 12:27

from django.db import migrations, models
import djongo.models.fields
import stock_sentiment_web_app.sentiment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocks', djongo.models.fields.EmbeddedModelField(model_container=stock_sentiment_web_app.sentiment.models.Stock, null=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(blank=True)),
                ('username', models.CharField(max_length=255)),
                ('retweets', models.PositiveIntegerField()),
                ('sentiment', models.FloatField()),
            ],
        ),
    ]
