# Generated by Django 2.2.7 on 2019-11-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(blank=True)),
                ('username', models.CharField(max_length=255)),
                ('retweets', models.PositiveIntegerField()),
                ('sentiment', models.FloatField()),
                ('stocks', models.ManyToManyField(to='sentiment.Stock')),
            ],
        ),
    ]
