# Generated by Django 2.2.7 on 2019-11-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0002_auto_20191120_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
