# Generated by Django 2.2.7 on 2019-11-26 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0004_auto_20191126_1224'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE or REPLACE view sentiment_stock_summary
                AS SELECT row_number() OVER () as id,
                       AVG(sentiment) as avg_sentiment,
                       stock_id
                FROM sentiment_tweet
                INNER JOIN sentiment_tweet_stocks sts ON sentiment_tweet.id = sts.tweet_id
                WHERE sentiment_tweet.created_at >= now()::date
                GROUP BY stock_id;
            """,
            "DROP VIEW sentiment_stock_summary;"
        )
    ]
