# Generated by Django 2.2.7 on 2019-12-04 22:02

from django.db import migrations, models
import django.db.models.deletion

from stock_sentiment_web_app.sentiment.models import IndustrySector


def populate_sectors(apps, schema_editor):
    initial_sectors = [
        'Energy',
        'Materials',
        'Industrial',
        'Consumer Discretionary',
        'Consumer Staple',
        'Health Care',
        'Financial',
        'Technology',
        'Communication Services',
        'Utilities',
        'Real Estate'
    ]
    sectors = (IndustrySector(name=sector_name) for sector_name in initial_sectors)
    IndustrySector.objects.bulk_create(sectors)


class Migration(migrations.Migration):
    dependencies = [
        ('sentiment', '0006_make_stock_summary_view_datewise'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSummary',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('avg_sentiment', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'sentiment_stock_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndustrySector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RunPython(populate_sectors),
        migrations.AddField(
            model_name='stock',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='sentiment.IndustrySector'),
        ),
    ]
