# Generated by Django 2.2.7 on 2019-12-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0008_create_industrysector_summary_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustrySectorSummary',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('avg_sentiment', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'sentiment_industrysector_summary',
                'managed': False,
            },
        ),
    ]
