version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  local_mongo_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: stock_sentiment_web_app_local_django
    depends_on:
      - postgres
      - mongo
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: stock_sentiment_web_app_production_postgres
    ports:
      - "12345:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  mongo:
    image: mongo
    container_name: 'mongodb'
    env_file:
      - ./.envs/.local/.mongo
    ports:
      - "27017:27017"
    volumes:
      - local_mongo_data:/data/db
